/**
 * /api/calls/example schedules transcript turns from a JSON manifest so the
 * example call renders through the same SSE path as a live call. The contract
 * we care about: the number of turns and their ordering match the manifest,
 * and the call.ended event fires after the audio finishes (manifest
 * `duration_ms` + a small buffer).
 *
 * Using fake timers + the real on-disk manifest (regenerated by
 * `pnpm example-calls:build`) so a manifest drift breaks the test.
 */
import { afterEach, beforeEach, describe, expect, test, vi } from 'vitest';

beforeEach(() => {
  vi.resetModules();
  vi.useFakeTimers();
  (globalThis as { __pulseLiveCallStore?: unknown }).__pulseLiveCallStore = undefined;
});

afterEach(() => {
  vi.useRealTimers();
  (globalThis as { __pulseLiveCallStore?: unknown }).__pulseLiveCallStore = undefined;
});

async function importRoute() {
  return await import('../app/api/calls/example/route');
}

describe('POST /api/calls/example', () => {
  test('rejects unknown scenario with 400', async () => {
    const { POST } = await importRoute();
    const res = await POST(new Request('http://localhost/api/calls/example?scenario=nope'));
    expect(res.status).toBe(400);
  });

  test('emits call.started immediately and turn.appended for every manifest turn in order', async () => {
    const { POST } = await importRoute();
    const store = await import('../lib/live-calls');
    const { readFile } = await import('node:fs/promises');
    const { join } = await import('node:path');

    const manifest = JSON.parse(
      await readFile(join(process.cwd(), 'public', 'example-calls', 'order.json'), 'utf8'),
    ) as { duration_ms: number; turns: { speaker: string; text: string; t_ms: number }[] };

    const events: { kind: string; turn?: { speaker: string } }[] = [];
    store.subscribeCallEvents((event) => events.push(event));

    const res = await POST(new Request('http://localhost/api/calls/example?scenario=order'));
    expect(res.status).toBe(200);
    const payload = (await res.json()) as { turns: number };
    expect(payload.turns).toBe(manifest.turns.length);

    // call.started fires synchronously inside the route handler.
    expect(events[0].kind).toBe('call.started');

    // Advance just past the last turn timestamp; every turn should now be in.
    const lastTurnAt = manifest.turns[manifest.turns.length - 1].t_ms;
    await vi.advanceTimersByTimeAsync(lastTurnAt + 1);

    const turnEvents = events.filter((e) => e.kind === 'turn.appended');
    expect(turnEvents).toHaveLength(manifest.turns.length);
    expect(turnEvents.map((e) => e.turn?.speaker)).toEqual(
      manifest.turns.map((t) => t.speaker),
    );

    // call.ended fires duration_ms + 500 after start. We've only advanced past
    // the last turn so far; finish the buffer to flush it.
    await vi.advanceTimersByTimeAsync(manifest.duration_ms + 500);
    expect(events[events.length - 1].kind).toBe('call.ended');
  });
});
